# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24e4986390619b535b9fefd4d7f8a4baa5a0b1a20ecdc1a8e75b0472aba794fbee77d7b7efd64c9ed2947d030d41e7b756d316553c0e57615eb6ed514d71b01d

test:
  secret_key_base: cd527e4f7ce5b02e7cf85435c24e9f8387523aec4345553e42b0de7a88c4ebf219c527e0bf9a3383e9cb931399ea695196f1b5b6532fb205daa6ac71640e9b7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
